<a href="https://colab.research.google.com/github/HENILCHOPRA/pytorch-learning/blob/main/pytorch_101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
import pandas as pd

In [ ]:
x = torch.tensor(3., requires_grad= True)
x

tensor(3., requires_grad=True)

In [ ]:
y = torch.tensor(2., requires_grad= True)
y

tensor(2., requires_grad=True)

In [ ]:
y.grad

In [ ]:
w = x * y + y
x.grad

In [ ]:
arr = np.array([[1,2],[3,4.]])

In [ ]:
z = torch.from_numpy(arr)

<h2>Regression model</h2>

In [ ]:
inputs = np.array(
    [[73,67,43],
     [91,88,64],
     [87,134,58],
     [102,43,37],
     [69,96,70]], dtype = 'float32'
)
inputs = torch.from_numpy(inputs)

In [ ]:
targets = np.array(
    [[56,70],
     [81,101],
     [119,133],
     [22,37],
     [103,119]], dtype = 'float32'
)
targets = torch.from_numpy(targets)

In [ ]:
w = torch.randn(2,3, requires_grad= True)
b = torch.randn(2, requires_grad = True)

print(w)
print(b)

tensor([[ 1.7645,  0.7065,  0.2973],
        [-0.4572, -1.3117,  0.4612]], requires_grad=True)
tensor([1.1350, 0.2044], requires_grad=True)


"@" represents matrix *multiplications*

In [ ]:
def model(x):
  return x @ w.t() + b

In [ ]:
predicts = model(inputs)
print(predicts)

tensor([[ 190.0653, -101.2284],
        [ 242.9068, -127.3198],
        [ 266.5655, -188.5982],
        [ 222.4955,  -85.7734],
        [ 211.5238, -124.9875]], grad_fn=<AddBackward0>)


<h2> Loss function </h2>

In [ ]:
targets - predicts

tensor([[-134.0653,  171.2284],
        [-161.9068,  228.3198],
        [-147.5655,  321.5982],
        [-200.4955,  122.7734],
        [-108.5238,  243.9875]], grad_fn=<SubBackward0>)

*tensor.numel() number of elements in the tensor*

In [ ]:
def mse(t1, t2):
  diff = t1 - t2
  return torch.sum(diff ** 2) / diff.numel() 

In [ ]:
loss = mse(targets, predicts)
print(loss)

tensor(37741.6484, grad_fn=<DivBackward0>)


<h2>Gradients</h2>


 **.*backward()***  computes gradients for tensors with ***requires_grad = True***

In [ ]:
loss.backward() 

In [ ]:
print(w.grad)
print(b.grad)

tensor([[ 13059.4346,  12408.7080,   7940.1284],
        [-18122.7695, -20672.1328, -12449.9453]])
tensor([ 150.5114, -217.5815])


In [ ]:
w.grad.zero_()
b.grad.zero_()

tensor([0., 0.])

<h2>Binding it all</h2>

In [ ]:
print(w)
print(b)

tensor([[ 1.6339,  0.5824,  0.2179],
        [-0.2760, -1.1050,  0.5857]], requires_grad=True)
tensor([1.1335, 0.2066], requires_grad=True)


In [ ]:
for i in range(100):
  preds = model(inputs)
  loss = mse(preds, targets)
  loss.backward() 
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

print(loss) 


tensor(3.0098, grad_fn=<DivBackward0>)


***USING PYTORCH***

In [ ]:
import torch.nn as nn
inputs = np.array(
    [[73,67,43],
     [91,88,64],
     [87,134,58],
     [102,43,37],
     [69,96,70],
     [73,67,43],
     [91,88,64],
     [87,134,58],
     [102,43,37],
     [69,96,70],
     [73,67,43],
     [91,88,64],
     [87,134,58],
     [102,43,37],
     [69,96,70]], dtype = 'float32'
)
targets = np.array(
    [[56,70],
     [81,101],
     [119,133],
     [22,37],
     [103,119],
     [56,70],
     [81,101],
     [119,133],
     [22,37],
     [103,119],
     [56,70],
     [81,101],
     [119,133],
     [22,37],
     [103,119]], dtype = 'float32'
)
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [ ]:
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader
import torch.nn.functional as F


In [ ]:
trainds = TensorDataset(inputs, targets)
trainds[:2]

(tensor([[73., 67., 43.],
         [91., 88., 64.]]), tensor([[ 56.,  70.],
         [ 81., 101.]]))

In [ ]:
batch_size = 5
traindl = DataLoader(trainds, batch_size, shuffle = True)

In [ ]:
for xb, yb in traindl:
  print(xb,yb)
  break

tensor([[ 69.,  96.,  70.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 91.,  88.,  64.],
        [ 91.,  88.,  64.]]) tensor([[103., 119.],
        [119., 133.],
        [ 22.,  37.],
        [ 81., 101.],
        [ 81., 101.]])


In [ ]:
model = nn.Linear(3,2) # 3 is size of input and 2 is size of output

print(model.weight)
print(model.bias)


Parameter containing:
tensor([[ 0.5046, -0.5365, -0.4938],
        [ 0.0522,  0.2542, -0.0322]], requires_grad=True)
Parameter containing:
tensor([ 0.0372, -0.5246], requires_grad=True)


In [ ]:
list(model.parameters()) 
# give out all the parameters of the model
# Here it is weights and bias 


[Parameter containing:
 tensor([[ 0.5046, -0.5365, -0.4938],
         [ 0.0522,  0.2542, -0.0322]], requires_grad=True),
 Parameter containing:
 tensor([ 0.0372, -0.5246], requires_grad=True)]

In [ ]:
def fit(model, epochs, loss_fn, opt):
  for epoch in range(epochs):
    for xb,yb in traindl:
      pred = model(xb)
      
      loss = loss_fn(pred, yb)

      loss.backward()

      opt.step()
      
      opt.zero_grad()

    # if epoch%10 ==0 :
    print(epoch,': ', loss.item())

In [ ]:
model = nn.Linear(3,2)
loss_fn = F.mse_loss
opt = torch.optim.SGD(model.parameters(), lr = 1e-5)
fit(model, 100, loss_fn, opt)

0 :  6108.3251953125
10 :  202.900146484375
20 :  153.0011444091797
30 :  107.14607238769531
40 :  84.56195831298828
50 :  44.398963928222656
60 :  28.98651695251465
70 :  24.339397430419922
80 :  37.756431579589844
90 :  9.665559768676758


In [ ]:
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
df = pd.read_csv("/content/housing.csv", header=None, delimiter=r"\s+",  names = column_names)
df.head()

CRIM    ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  MEDV
0  0.00632  18.0   2.31     0  0.538  ...  296.0     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242.0     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242.0     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222.0     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222.0     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [ ]:
inputs = df.drop(['MEDV'], axis = 1)
targets = df['MEDV']
inputs = torch.from_numpy(inputs.to_numpy(dtype = 'float32'))
targets = torch.from_numpy(targets.to_numpy(dtype = 'float32'))

In [ ]:
trainds = TensorDataset(inputs, targets)
batch_size = 253
traindl = DataLoader(trainds, batch_size, shuffle = True)

model = nn.Linear(13, 1)
loss_fn = F.mse_loss
opt = torch.optim.SGD(model.parameters(), lr = 1e-5)
fit(model, 10, loss_fn, opt)

0 :  60019.53125
1 :  47667184.0
2 :  35618791424.0
3 :  28076614352896.0
4 :  2.023204474322944e+16
5 :  1.6025913038951416e+19
6 :  1.226305971684989e+22
7 :  9.280503909094064e+24
8 :  7.27497262057502e+27
9 :  5.558147072390752e+30


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: UserWarning: Using a target size (torch.Size([253])) that is different to the input size (torch.Size([253, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  
